name: cs lab_4 pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'

    - name: add packages
      run: |
        dotnet add ./program/lab_4.csproj package NAudio
        dotnet add ./test/lab_4_test.csproj package NAudio
        dotnet add ./test/lab_4_test.csproj package Moq

    - name: restore dependencies
      run: |
        dotnet restore ./program/lab_4.csproj
        dotnet restore ./test/lab_4_test.csproj

    - name: build 
      run: |
        dotnet build ./program/lab_4.csproj --no-restore
        dotnet build ./test/lab_4_test.csproj --no-restore

    - name: run tests
      run: |
        dotnet test ./test/lab_4_test.csproj --no-build --verbosity normal
